version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: caas
    ports: ["5432:5432"]

  redpanda:
    image: redpandadata/redpanda:latest
    command: ["redpanda","start","--overprovisioned","--smp","1","--memory","1G","--reserve-memory","0M","--check=false"]
    ports: ["9092:9092","9644:9644"]

  api-gateway:
    build:
      context: ../services/api-gateway   # 👈 note the ../
      dockerfile: Dockerfile
    env_file:
      - ../.env                          # 👈 ../ points at repo root .env
    ports: ["8080:8080"]
    depends_on: [postgres]
    
  migrator:
    image: node:20-alpine
    working_dir: /app
    env_file:
      - ../.env
    depends_on:
      - postgres
    volumes:
      - ../scripts/migrations:/app
    command: sh -c "corepack enable && pnpm i && pnpm run migrate:up"
